
-- MEMBER TABLE
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(15),
    MEMBER_PW VARCHAR2(15),
    MEMBER_NAME VARCHAR2(15),
    MEMBER_AGE NUMBER,
    MEMBER_EMAIL VARCHAR2(45),
    CONSTRAINT MEMBER_ID_PK PRIMARY KEY(MEMBER_ID)
);

-- MEMBERBORAD TABLE
CREATE TABLE MEMBERBOARD (
    BOARD_NUM NUMBER,
    BOARD_ID VARCHAR2(20),
    BOARD_PASS VARCHAR2(15),
    BOARD_SUBJECT VARCHAR2(50),
    BOARD_CONTENT VARCHAR2(2000),
    BOARD_FILE VARCHAR2(50),
    BOARD_RE_REF NUMBER,
    BOARD_RE_LEV NUMBER,
    BOARD_RE_SEQ NUMBER,
    BOARD_READCOUNT NUMBER,
    BOARD_DATE DATE,
    CONSTRAINT MEMBERBOARD_BOARD_ID_PK PRIMARY KEY(BOARD_NUM)
);